apiVersion: apps/v1
kind: Deployment
metadata:
  name: user05-atitanj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user05-atitanj
  template:
    metadata:
      labels:
        app: user05-atitanj
    spec:
      containers:
        - name: user05-atitanj
          image: ghcr.io/atitanj/aj
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user05-atitanj
  labels:
    app: user05-atitanj
spec:
  selector:
    app: user05-atitanj
  ports:
   - name: web-port
     protocol: TCP
     port: 8081
     targetPort: 80
  type: ClusterIP