apiVersion: apps/v1
kind: Deployment
metadata:
  name: aj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aj
  template:
    metadata:
      labels:
        app: aj
    spec:
      containers:
        - name: aj-server
          image: ghcr.io/atitanj/aj
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aj-service
  labels:
    app: aj-service
spec:
  selector:
    app: aj
  ports:
   - name: web-port
     protocol: TCP
     port: 8081
     targetPort: 80
  type: ClusterIP